version: 1.0.0.{build}

branches:
    only:
        - master

skip_tags: true

assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "1.0.0.{build}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

build:
    project: Teleporter\Teleporter.sln

before_build:
    - git.exe submodule update --init --recursive
    - nuget restore Teleporter\Teleporter.sln
    - nuget restore ElectronicObserverExtended\ElectronicObserver.sln
    - mkdir output
    - ps: (Get-Content Teleporter\Teleporter.cs -Encoding UTF8).replace("<BUILD_VERSION>", "$env:APPVEYOR_BUILD_VERSION") | Set-Content Teleporter\Teleporter.cs -Encoding UTF8

artifacts:
    - path: output
      name: Teleporter-$(APPVEYOR_BUILD_VERSION)

deploy:
  provider: GitHub
  auth_token:
    secure: LRyrixQEgYtxLDVKSCkxkjmAzMS4gi+DABeBjkT1r9Tunat6Satr15XuwkCWwoY0
  artifact: /.*/
  on:
    branch: master
